version: '3.9'

services:
  app:
    build: .
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=local
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/storage/database.sqlite
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - app-network

  node:
    image: node:20
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - VITE_APP_NAME=Laravel
    command: sh -c "npm install && npm run build"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
