services:
  app:
    build: .
    container_name: laravel-app
    volumes:
      - .:/var/www/html
    networks:
      - app-network
    expose:
      - 9000  # Ensure that PHP-FPM's port is exposed within the Docker network

  nginx:
    image: nginx:alpine
    container_name: nginx-server
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
