version: '3.8'

services:
  app:
    build: .
    container_name: laravel-app
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
