version: '3.8'

services:
  app:
    build: .
    container_name: laravel-app
    volumes:
      - .:/var/www/html
    networks:
      - app-network

  nginx:
    build: .
    container_name: nginx-server
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8000:80
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
