version: "3"
networks:
  application:
    driver: bridge
services:
  app:
    build:
      context: . # Ensure this points to the correct Laravel project folder
      dockerfile: Dockerfile
    container_name: mybackend
    ports:
      - 8000:8000
    volumes:
      - .:/app  # Mount your Laravel project files
      - db_data:/app/database  # Use the defined Docker volume for SQLite database
    networks:
      - application
    entrypoint: ['/bin/sh', '-c']
    command:
      - |
        composer install
        php artisan migrate --force
        php artisan serve --host=0.0.0.0 --port=8000
volumes:
  db_data: # Explicitly define the db_data volume
